### PR TITLE
updated vendors - bug in urfave/cli

### LINKED ISSUE #53: Documentation?
No documentation? URL to github.io is dead

### PR DESCRIPTION
**Pull request by dsielert**
Fixes #53  bug due to outdated vendors (updated all vendors) urfave/cli was appending ENV variables instead of overwriting

### CODE REVIEW

**Comment by dsielert** [comment]
I really should've created new issue for this but nonetheless it fixes the consul endpoints issue

**Comment by tboerger** [comment]
I think I will simply replace the whole vendoring folder by go modules. That will also reduce the repo size.

**Comment by dsielert** [comment]
yeah probably a good idea, I was just trying to get this to work, I've not a whole lot exp with GO , sorry
thought I'd share

**Comment by tboerger** [comment]
But than you for the interest to contribute a fix. I didn't even know if somebody is using that project at all beside me :D

**Pull request closed without merging**
